"""Update Company model with new fields

Revision ID: 05b50ffd91dc
Revises: a4f5903942bc
Create Date: 2024-11-23 16:24:30.665304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b50ffd91dc'
down_revision: Union[str, None] = 'a4f5903942bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'document_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'document_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
