"""Nuevos campos para el modelo compañia

Revision ID: b307a62be1d1
Revises: a4f5903942bc
Create Date: 2024-11-23 17:00:57.442593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b307a62be1d1'
down_revision: Union[str, None] = 'a4f5903942bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('country_of_residence', sa.String(), nullable=True))
    op.drop_constraint('employees_document_id_key', 'employees', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('employees_document_id_key', 'employees', ['document_id'])
    op.drop_column('companies', 'country_of_residence')
    # ### end Alembic commands ###
