"""Agregando campos de fechas de asignacion, limite y realizacion

Revision ID: bbb3459a9ee5
Revises: b307a62be1d1
Create Date: 2024-11-23 23:55:55.732939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb3459a9ee5'
down_revision: Union[str, None] = 'b307a62be1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('title', sa.String(), nullable=False))
    op.add_column('evaluations', sa.Column('assigned_date', sa.DateTime(), nullable=True))
    op.add_column('evaluations', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('evaluations', sa.Column('completion_date', sa.DateTime(), nullable=True))
    op.add_column('evaluations', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'is_completed')
    op.drop_column('evaluations', 'completion_date')
    op.drop_column('evaluations', 'due_date')
    op.drop_column('evaluations', 'assigned_date')
    op.drop_column('evaluations', 'title')
    # ### end Alembic commands ###
